python ./run_summarization.py \
    --model_name_or_path ./indicbart-ner/output/checkpoint-56619 \
    --lang hi_IN \
    --forced_bos_token=tokenizer.lang_code_to_id["hi_IN"] \
    --max_source_length 1024 \
    --max_target_length 40 \
    --output_dir ./indicbart-ner/output \
    --source_prefix ". summarize: " \
    --ner_prefix "entity: " \
    --do_predict \
    --test_file hindi_val_ner_1024.csv \
    --num_beams 4 \
    --predict_with_generate \
    --dataloader_num_workers 1 \
    --logging_strategy "epoch" \
    --save_strategy "epoch" \
    --seed 42 \
    --use_fast_tokenizer False \
    --do_ner \
    --ner_column ner_str \
    --summary_column summary \
    --resume_from_checkpoint ./indicbart-ner/output/checkpoint-56619 \
    --text_column text $@
